### ISSUE TITLE
Deploy lbryumx as real live server, and only release on tags instead of every commit

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbryumx#10]
- [x] make sure prod server has a domain name (ask Niko about that)

**Comment by shyba** [comment]
https://hub.docker.com/r/lbry/lbryumx/tags/
Done. Changing the production server to use "stable" tag instead of "latest" on the next night (less traffic).

**Comment by shyba** [comment]
DNS; lbryumx1.lbry.io:50001

**Comment by shyba** [comment]
@lyoshenka lbryumx1 now uses stable tag (the latest tagged release), this is done. I think we should open a separated issue to have the Ansible working later, but I guess the tag and the update is enough for the scope of this issue.

**Comment by lyoshenka** [comment]
sounds good, please do so :-)
