### ISSUE TITLE
New blockhash argument for lbrycrd RPC commands

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbryumx#23]
There will now be an optional new blockhash argument for the below lbrycrd RPC commands once this PR is merged https://github.com/lbryio/lbrycrd/pull/189 :

getvalueforname
getclaimsforname
getclaimsintrie
getclaimtrie
getnameproof

This solves the problem where lbryumx must make multiple calls to lbrycrd with the assumption that lbrycrd is maintaining a consistent claimtrie state. However, lbrycrd may have incremented the block in the mean time, making this assumption false. By passing the same blockhash as an argument to these functions, consistent claimtrie state can be maintained.

**Comment by eukreign** [comment]
Issue moved to [lbryio/lbry #1582](https://github.com/lbryio/lbry/issues/1582) via [**ZenHub**](https://www.zenhub.com/)
